data_dir: /data/ephemeral/home/data
model_dir: ./trained_models/Agumentation/base
device: cuda
# only for train #

image_size: &image_size 2048
input_size: &input_size 1024

batch_size: 8
num_workers: 8

seed : 42
learning_rate: 1e-3
max_epoch: 150
save_interval: 5

# Custom Dataset 사용시 주석 해제
transform: 
  LongestMaxSize:  # albumentations의 함수명 정확하게 작성
    max_size: *image_size # 해당 함수의 인자 작성
  SmallestMaxSize:
    max_size: *input_size
  Normalize: {}
  Rotate:
    limit: 15 
    border_mode: 1
  Perspective:  
    fit_output: True
    pad_mode: 1


#------------------------------------------------------------#
# save parameters for Gsheet & Wandb #
experiment_name: Agumentation
experiment_detail: Add Rotate and Perspective

#------------------------------------------------------------#
# train, validation json file
validation: True
train_ann : train_fold_1
val_ann : val_fold_1