data_dir: /data/ephemeral/home/data
model_dir: ./trained_models
device: cuda
# only for train #
#------------------------------------------------------------#
# save parameters for Gsheet #
experiment_name: outlier_remove
experiment_detail: baseline code + remone
image_size: 2048
input_size: 1024

batch_size: 8
num_workers: 8

seed : 42
learning_rate: 1e-3
max_epoch: 150
save_interval: 5