data_dir: /data/ephemeral/home/data
model_dir: ./trained_models
device: cuda
# only for train #

# save parameters for Gsheet & Wandb #
experiment_name: base 학습
experiment_detail: base 점수 확인용

# train, validation json file
validation: True
train_ann : train_fold_1
val_ann : val_fold_1

image_size: 2048
input_size: 1024

batch_size: 8
num_workers: 8

seed : 42
learning_rate: 1e-3
max_epoch: 150
save_interval: 5

# Custom Dataset 사용시 주석 해제
# transform: 
#   LongestMaxSize:  # albumentations의 함수명 정확하게 작성
#     max_size: 1024 # 해당 함수의 인자 작성
#   PadIfNeeded:
#     min_width: 1024
#     min_height: 1024
#     border_mode: 1
#   Normalize:
#     mean: [0.5, 0.5, 0.5]
#     std: [0.5, 0.5, 0.5]



