data_dir: /data/ephemeral/home/data
model_dir: ./trained_models

experiment_name: UFO2COCO
experiment_detail: COCO Segmentation point 사용
image_size: 2048
input_size: 1024

batch_size: 8
num_workers: 8

learning_rate: 1e-3
max_epoch: 150
save_interval: 5