data_dir: /data/ephemeral/home/SR_data
model_dir: ./trained_models/SR
device: cuda

# only for train #

# save parameters for Gsheet & Wandb #
experiment_name: Super_Resolution
experiment_detail: SR 최신 full data

# train, validation json file
validation: False
train_ann : train
val_ann : val_fold_1

image_size: &image_size 4096
input_size: &input_size 2048

batch_size: 2
num_workers: 8

learning_rate: 1e-3
max_epoch: 150
save_interval: 5

# Custom Dataset 사용시 주석 해제
transform: 
  LongestMaxSize:  # albumentations의 함수명 정확하게 작성
    max_size: *image_size # 해당 함수의 인자 작성
# 인자로 넘겨줄 것이 없다면 --> 함수명 : {}
# Normalize는 Dataset에서 자동 추가되므로 추가 X